# Generated by Django 4.2.3 on 2023-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('datetime_field', models.DateTimeField(auto_now_add=True)),
                ('photo_field', models.ImageField(upload_to='student_photos/')),
                ('phone_field', models.CharField(max_length=20)),
                ('description_field', models.TextField()),
                ('success', models.BooleanField(default=True)),
            ],
        ),
    ]
